# Generated by Django 4.0.3 on 2022-04-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date_borrow',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
