# Generated by Django 4.0.3 on 2022-05-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_alter_borrow_return_date_borrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ancien', 'ancien'), ('frequence', 'frequence')], default='ancien', max_length=10)),
                ('modalilte', models.CharField(choices=[(7, 'semaine'), (30, 'mois'), (365, 'annee')], default=30, max_length=10)),
                ('valeur', models.IntegerField(default=1)),
            ],
        ),
    ]
