# Generated by Django 4.0.3 on 2022-05-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_parametre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='modalilte',
            field=models.CharField(choices=[(7, 'semaine'), (30, 'mois'), (365, 'annee')], default='mois', max_length=10),
        ),
    ]
