# Generated by Django 4.0.3 on 2022-05-14 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_category'),
        ('borrow', '0004_alter_parametre_modalilte'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='readPoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.readpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametre',
            name='modalilte',
            field=models.CharField(choices=[('7', 'semaine'), ('30', 'mois'), ('365', 'annee')], default='30', max_length=10),
        ),
    ]
