# Generated by Django 4.0.4 on 2022-05-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_commentaires'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['notes']},
        ),
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.IntegerField(null=True),
        ),
    ]
