# Generated by Django 4.0.3 on 2022-04-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=200)),
                ('action_type', models.SmallIntegerField(choices=[(1, 'Création'), (2, 'Modification'), (3, 'Suppression'), (4, 'Visite')])),
                ('visited_url', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('action_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
